# Site settings
title: "Praxis Efficax"
description: "Become an effective product-centric organization."
baseurl: ''
url: ''
# google_analytics: 'UA-XXXXXX-X'

# Build settings
markdown: kramdown

exclude:
  - assets
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

permalink: "/:title/"

plugins: [jekyll-paginate]

paginate: 10
